# Generated by Django 5.1.7 on 2025-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0002_processedimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processedimage",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="processedimage",
            name="patient_dni",
            field=models.CharField(default="DESCONOCIDO", max_length=20),
            preserve_default=False,
        ),
    ]
