# Generated by Django 5.1.9 on 2025-06-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_remove_processedimage_patient_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalImage',
        ),
    ]
