services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # En dev, usa runserver para que Django maneje static + CSRF correctamente
    command: python backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
    volumes:
      - ./media:/app/backend/media
      - ./staticfiles:/app/backend/staticfiles
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
    depends_on:
      - inference

  inference:
    build:
      context: .
      dockerfile: Dockerfile.inference
    ports:
      - "8001:8001"
    volumes:
      - models:/app/modelos
      - outputs:/app/outputs

volumes:
  media:
  staticfiles:
  models:
  outputs: