services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # En dev, usa runserver para que Django maneje static + CSRF correctamente
    command: python backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
    volumes:
      - .:/app
    depends_on:
      - inference

  inference:
    build:
      context: .
      dockerfile: Dockerfile.inference
    ports:
      - "8001:8001"
    volumes:
      - ./outputs:/app/outputs
  test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: bash -c "pip install pytest pytest-django && pytest tests/"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONPATH=.
    volumes:
      - .:/app

volumes:
  media:
  staticfiles:
  outputs:
