services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - inference

  inference:
    build:
      context: .
      dockerfile: Dockerfile.inference
    ports:
      - "8001:8001"
    volumes:
      - ./outputs:/app/outputs
  test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: bash -c "pip install pytest pytest-django coverage && coverage run --rcfile=.coveragerc -m pytest tests/ && coverage report --rcfile=.coveragerc && coverage html --rcfile=.coveragerc"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONPATH=.
    volumes:
      - .:/app

volumes:
  media:
  staticfiles:
  outputs:
